### ISSUE TITLE
What's the purpose of the return statement in scanner

### ISSUE THREAD

**Issue by spapas** [takeflight/wagtail-linkchecker#16]
Could you clarify why this return statement is here: 

https://github.com/neon-jungle/wagtail-linkchecker/blob/c94114b0c91e90af778fad053d27228a8e4eb980/wagtaillinkchecker/scanner.py#L125

I think that it should be removed in order to allow checking all pages for broken links instead of just the homepage. Or I am missing something ?

**Comment by seb-b** [comment]
I'm not the original author but yes, I can't see any reason not to get rid of it. Maybe it was meant to be a `continue`?
