### ISSUE TITLE
Request times out in Heroku

### ISSUE THREAD

**Issue by alexgleason** [takeflight/wagtail-linkchecker#7]
I tried deploying to a Heroku site (@po5i's fork, but I'm guessing it happens in the older version also) and the request to `/admin/link-checker/scan/` takes longer than 30 seconds to complete, [meaning Heroku kills it](https://devcenter.heroku.com/articles/request-timeout).

This is the output:

>2018-09-27T00:40:52.792633+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/admin/link-checker/scan/" host=www.projecttier.org request_id=f34f2083-3ca1-423c-97e2-9c7786b3c2ba fwd="71.230.111.204" dyno=web.1 connect=1ms service=30000ms status=503 bytes=0 protocol=https
2018-09-27T00:40:53.524928+00:00 app[web.1]: [2018-09-27 00:40:53 +0000] [4] [CRITICAL] WORKER TIMEOUT (pid:12)
2018-09-27T00:40:53.526810+00:00 app[web.1]: [2018-09-26 20:40:53 -0400] [12] [INFO] Worker exiting (pid: 12)
2018-09-27T00:40:53.763977+00:00 app[web.1]: [2018-09-27 00:40:53 +0000] [20] [INFO] Booting worker with pid: 20

ProjectTIER/projecttier.org#62

This is my first time using Celery, but isn't the point of it to prevent this very thing? I'd expect that clicking "Scan" immediately takes you back to the index with a "Scanning in progress..." message or something, and you can return to the page later to see the results.

**Comment by po5i** [comment]
It's supposed to do so, but I struggled with Celery also and that's why I switched to Django rq. It's easier to setup, you can take a look at my django-rq branch

**Comment by po5i** [comment]
BTW, do you started the celery workers?

**Comment by seb-b** [comment]
Yep this should be ran async.
I haven't had a chance to look into the issue, where are you starting the scan from? The `Conduct Scan` button from the index?

**Comment by alexgleason** [comment]
>where are you starting the scan from? The Conduct Scan button from the index?

Yes, exactly.

>BTW, do you started the celery workers?

I'm not totally sure... I'm doing this on Heroku and am a total beginner with both Celery and Redis. But on both Heroku and on my dev machine, clicking the button makes my cursor spin and it *looks* like I'm sitting there waiting for an HTTP request to finish. In both cases it takes longer than 30 seconds. But on my local machine, it doesn't time out and eventually finishes.

**Comment by seb-b** [comment]
The view that handles the button press is found [here](https://github.com/takeflight/wagtail-linkchecker/blob/master/wagtaillinkchecker/views.py#L90)

Something must be taking too much time before the redirect is returned, probably the best place to start.

**Comment by alexgleason** [comment]
Thanks for looking into this!

**Comment by alexgleason** [comment]
So, at what point does Celery actually come into play? The `run_scan` view calls `broken_link_scan(site)` which loops through every page, calling `ScanLink.check_link()`

I don't know Celery, but I'm guessing `check_link()` is the point where it actually happens.

In its current state, it blocks the HTTP request to `/scan` from completing. It takes about 40 seconds to get a response.

Is it possible to make the Celery task happen a level up? eg, so that even looping through the pages is handled by Celery? Or it is just blocking execution when it shouldn't be?

**Comment by seb-b** [comment]
> I don't know Celery, but I'm guessing check_link() is the point where it actually happens.

Yep, celery comes into play [here](https://github.com/neon-jungle/wagtail-linkchecker/blob/master/wagtaillinkchecker/models.py#L108)

So basically it gathers all the page models then kicks off that task for each one. That shouldn't take 40 seconds, unless there's a long delay to the database or a ridiculous number of pages?

Unless celery isn't being utilised properly and it's not truely async.. 

> Is it possible to make the Celery task happen a level up? eg, so that even looping through the pages is handled by Celery?

Yeah this is possible, you could create a new task that does the page gathering and then call that from the view

**Comment by alexgleason** [comment]
>That shouldn't take 40 seconds, unless there's a long delay to the database or a ridiculous number of pages?

There are 151 pages on the site:

```
project_tier=# SELECT COUNT(*) FROM wagtailcore_page;
 count 
-------
   151
(1 row)
```

This leads me to believe that looping through the pages definitely isn't the problem.

The database isn't slow. Here's the live site: https://www.projecttier.org/ Not blazing fast, but shouldn't choke on a SELECT statement.

## database stuff

https://github.com/neon-jungle/wagtail-linkchecker/blob/b696d2fefe053a830b83160325b2ab1c502d88ac/wagtaillinkchecker/scanner.py#L119

^ This is a SELECT statement. I don't think it chokes here.

https://github.com/neon-jungle/wagtail-linkchecker/blob/b696d2fefe053a830b83160325b2ab1c502d88ac/wagtaillinkchecker/scanner.py#L122-L128
^ This could... potentially be a problem? I imagine it's doing 151 SELECT statements followed by up to 151 INSERTs.

I'm not sure why it's doing the SELECTs. For inserting them, I think it would make more sense to use [bulk_create()](https://docs.djangoproject.com/en/dev/ref/models/querysets/#bulk-create) so all entries are added in one transaction. Maybe something like:

```python
links = []  # somewhere earlier
# ...
links.append(ScanLink(url=page.full_url, page=page, scan=scan))
# ...
ScanLink.objects.bulk_create(links)  # somewhere later
```

This stuff is all happening **before Celery** comes into play.

**Comment by alexgleason** [comment]
I just installed django debug toolbar and gave it a try. It says 285 queries in 194.03 ms. Meanwhile the whole page takes 28.66 seconds to load.

So, I vastly overestimated the impact 285 queries would have. This isn't the problem, it's something else.

![Screenshot from 2019-03-18 18 23 35](https://user-images.githubusercontent.com/3639540/54567663-f9756880-49aa-11e9-861e-9d047ca0521a.png)
![Screenshot from 2019-03-18 18 23 07](https://user-images.githubusercontent.com/3639540/54567664-fa0dff00-49aa-11e9-9f77-22993b4e6661.png)
![Screenshot from 2019-03-18 18 22 02](https://user-images.githubusercontent.com/3639540/54567665-fa0dff00-49aa-11e9-8172-dd909338b258.png)
